### ISSUE TITLE
Compiled Version

### ISSUE THREAD

**Issue by bbakermmc** [warrenseine/prettier-plugin-csharp#1]
Can you provide a compiled version that we can just put in the node_modules to use.  Trying to get antlr to run on windows isnt working form me.

**Comment by warrenseine** [comment]
Actually, the doc is a little outdated. The compiled parser is indeed checked in, you don’t have to run ANTLR yourself.

Note that the plugin is still in development and will not format anything else than toy code for the moment.

**Comment by warrenseine** [comment]
I just published a first version of the package to NPM: https://www.npmjs.com/package/prettier-csharp

Again, this is rough, so don't expect it to work against your actual C# code.

**Comment by grofit** [comment]
Can we update the docs to reflect the current usage as it still says that it needs ANTLR etc

**Comment by warrenseine** [comment]
Sure! I'll do that in the coming days as I'm about to push an "alpha" version.
