### ISSUE TITLE
How to install and use as plugin in VSCode?

### ISSUE THREAD

**Issue by kristianmandrup** [warrenseine/prettier-plugin-csharp#10]
I found this post on [prettier plugins](https://prettier.io/docs/en/plugins.html) on the prettier.io site, but not quite sure how to put it into effect in a C# project.

I also found this post on how to [configure prettier](https://www.39digits.com/configure-prettier-and-eslint-in-visual-studio-code/)

Coming from a NodeJS and JS background, I assumes I'd have to install prettier and the plugin in `packages.json` of my C# project root as dev dependencies.

Not sure if I should then use the CLI or the API option? Is it possible with direct integration in the IDE/Editor, ie. auto format on save as per the usual `settings.json` prettier setting?

Would be great if the Readme could be more clear on this. I know the plugins are beta.
Great work!

Cheers :)

**Comment by kristianmandrup** [comment]
Ah, it works with Editor integration (on Save) after running the two commands suggested.
Awesome! Would be nice if it could be more clear that all the usual benefits of prettier will be available out of the box on installation of a plugin :)

**Comment by warrenseine** [comment]
While renaming the project, I updated (and simplified) the commands. I will also add a section for editor integration, but will try to keep it simple because I want it to be vendor-agnostic.

Thanks for reporting!
