### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by MattKunze** [warrenseine/prettier-plugin-csharp#11]
This is similar to #10, the [Prettier docs](https://prettier.io/docs/en/plugins.html) specify:

> Plugins are automatically loaded if you have them installed in the same node_modules directory where prettier is located. Plugin package names must start with @prettier/plugin- or prettier-plugin- to be registered.

The VS Code extension seems to have some open problems with plugins (https://github.com/prettier/prettier-vscode/issues/395), but in Atom at least it will auto-format on save if I manually rename the folder in node_modules to 'prettier-csharp-plugin'

You can also see that it's registered automatically with `prettier --support-info` (I found this through https://github.com/prettier/prettier-atom/issues/395#issuecomment-378357499):

```
$ ./node_modules/.bin/prettier --support-info | grep '"\.cs'
      "extensions": [".css"],
      "extensions": [".cs", ".cake", ".cshtml", ".csx"],
```

**Comment by warrenseine** [comment]
I actually read about it today morning! It's done:
- Repository renamed
- New package published
- Previous package deprecated
- README updated
- `prettier --write File.cs` tested successfully!
