### ISSUE TITLE
Sorting 'System' first is deprecated

### ISSUE THREAD

**Issue by janaagaard75** [warrenseine/prettier-plugin-csharp#12]
I don't think it's recommended to sort `System` namespaces first any more. I believe [it has been like this since Visual Studio 2012](https://stackoverflow.com/q/14829853/37147). So I think `prettier-plugin-csharp` should adhere that new standard, and sort System namespace alphabetically.

(Is this configurable? I couldn't find any documentation about configuring `prettier-plugin-csharp`.)

**Comment by warrenseine** [comment]
I don’t have a strong opinion about it but it’s the style of most codebases, including Roslyn. I’ll have to collect more data before deciding if it should be switched off by default or even configurable. As you know, one of the motivations behind Prettier is to leave very little space for choice.

In the meantime, I think you can disable this behavior by adding a preprecessor directive (it won’t sort them at all).

**Comment by janaagaard75** [comment]
Thanks for the quick response. I think you're right in that most C# code is still using the default of sorting the System namespace first, so for most people `prettier-plugin-csharp` is doing the correct thing. I still think that this should be configurable, but I there are probably other things that are more urgent than this.
