### ISSUE TITLE
Support for C# 7 local functions

### ISSUE THREAD

**Issue by sicsix** [warrenseine/prettier-plugin-csharp#13]
Great work on this.

I've noticed there is currently no support for C# 7 local functions . Could this be added?
[https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions](url)

**Comment by warrenseine** [comment]
That shouldn’t be much work on the current parser, but I won’t be able to work on it right now. I’ll ping you when it’s ready.

**Comment by warrenseine** [comment]
Sorry for the lack of updates. I still haven’t taken the time to tackle this, but I will :)
