### ISSUE TITLE
String interpolation handled incorrectly

### ISSUE THREAD

**Issue by benjaminwinokur** [warrenseine/prettier-plugin-csharp#14]
String interploation with the '$' character does not work properly. It only fails when the line length is longer than the specified limit.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated

Input:
> Logging.Log.Error($"Some error message text:  ({someVariableValue} did not work)");

Output:

> Logging
>&nbsp;&nbsp;.Log
>&nbsp;&nbsp;.Error($"Some error message text: ({
>&nbsp;&nbsp;someVariableValue} did not work)");

Expected Output:

> Logging.Log.Error(
> &nbsp;&nbsp; $"Some error message text: ({someVariableValue} did not work)");

Ideal Output:

> Logging.Log.Error($"Some error message " +
> &nbsp;&nbsp; $" text: ({someVariableValue} did not work)");

**Comment by warrenseine** [comment]
Thanks for this bug report (which I somehow totally skipped until now).

I can’t look right now but I’d encourage anyone to try and contribute a fix. Otherwise, I’ll check when I’m back from holidays.
