### ISSUE TITLE
Can I run this directly from Visual Studio? Are there plans for an extension?

### ISSUE THREAD

**Issue by shootdaj** [warrenseine/prettier-plugin-csharp#15]
I would be interested in contributing as well.

**Comment by warrenseine** [comment]
There is no explicit plan. You should probably ask on https://github.com/prettier/prettier-vscode or https://github.com/madskristensen/JavaScriptPrettier if they can run Prettier plugins, so we’d have a single extension to format JavaScript, TypeScript, and C#.

**Comment by robinmanuelthiel** [comment]
For reference: https://github.com/prettier/prettier-vscode/issues/395

**Comment by warrenseine** [comment]
Wow, great, I see that it was implemented a few days ago! I'd love if you could try it @shootdaj.
