### ISSUE TITLE
Are you accepting contributors?

### ISSUE THREAD

**Issue by CharlesTaylor7** [warrenseine/prettier-plugin-csharp#16]
I was fixing to write a C# formatter myself to keep me sane at work. This project looks like it's most of the way there. 

Would you be open to having contributors?
Or at the very least would you mind if I forked the project and continued development on it?

I didn't see any license in the Repo, so I wanted to check with you before forking the project.

**Comment by warrenseine** [comment]
There should be an MIT license, I forgot it. Contributions are welcome !

**Comment by CharlesTaylor7** [comment]
That's great!
I've opened a pull request to include an MIT license with your copyright. https://github.com/warrenseine/prettier-plugin-csharp/pull/17

From here, I'm planning to address the open issue about handling C#7 local methods.
