### ISSUE TITLE
Mixed tabs & spaces

### ISSUE THREAD

**Issue by CharlesTaylor7** [warrenseine/prettier-plugin-csharp#25]
The `*.g4` antlr files have spaces mixed with tabs. I've deduced based on your commits, that your using a tab width of 4 spaces; whereas I have been using a tab width of 2 spaces for these files. To make matters worse, Github uses a tab width of 8 spaces by default.

I'd like to normalize to pure tabs or pure spaces, with my preference towards the latter.
I can submit a PR to normalize everything, or we can do a more fancy [git-filter-branch](https://git-scm.com/docs/git-filter-branch) to normalize the whole git log.

What do you think?

**Comment by warrenseine** [comment]
Just normalize to space. Don’t worry about Git history.

I initially wanted to avoid making changes to the grammar so I could rebase on upstream easily, but I don’t think it’s possible anymore anyway. And the original grammar hasn’t changed much anyway.
