### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by OneCyrus** [warrenseine/prettier-plugin-csharp#3]
with the version on npm i get the following error for every cs file when running ``` yarn prettier --plugin=prettier-csharp --parser=cs --write "**/*.cs"```

```
[error] GraphQL\Customer\Service\Client\Devices\Assignments\AssignmentResultModel.cs: TypeError: Cannot read property '0' of undefined
[error]     at FastPath.call (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:9945:18)
[error]     at printCompilationUnit (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier-csharp\src\printer.js:20:38)
[error]     at Object.printNode [as print] (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier-csharp\src\printer.js:3269:14)
[error]     at genericPrint (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:10130:18)
[error]     at C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:10076:16
[error]     at Object.printComments (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:9838:17)
[error]     at printGenerically (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:10075:22)
[error]     at printAstToDoc (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:10087:16)
[error]     at coreFormat (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:10414:16)
[error]     at format (C:\Code\My.Project\src\My.Project.Portal\node_modules\prettier\bin-prettier.js:10572:16)
```

**Comment by warrenseine** [comment]
The version on npm is working on very specific, non-production use cases. Consider it like a demo.

Over the past few months, I’ve been working closely with the Prettier team to be able to parse preprocessor directives from Prettier, which is a much have for any serious C# code base. In the meantime, the plugin has not evolved, so it’s still unusable. I’m working on getting it back on track.

**Comment by crohlfs** [comment]
It looks like I got around this error by disabling the external alias and global attribute printing, obviously a better fix would be to make it handle not having these sections in the code, but right now this is working great for my case.

I'm using this as part of a project for transpiling react typescript components to tag helpers and it really cleans up the output a lot.

Would you like any help fixing this issue?

**Comment by warrenseine** [comment]
I've published a new minor version on NPM, which is aligned with this repository. Not sure it fixes the issues you're encountering.

I'm working on improving some indentation issues, and have been running Prettier C# against medium-sized real-life code without the issue you're mentioning, but I've fixed a similar bug: https://github.com/warrenseine/prettier-csharp/commit/9074758fe27318fe2fe5f3c56404a27cb6dc5dcc. Can you test again? If not, I'd welcome any contribution that improves this project!

**Comment by crohlfs** [comment]
Awesome, that fixed it for me :+1:

**Comment by OneCyrus** [comment]
thanks, it runs now and formats most files!
