### ISSUE TITLE
Comments inside empty class definitions don't get printed

### ISSUE THREAD

**Issue by CharlesTaylor7** [warrenseine/prettier-plugin-csharp#30]
```csharp
class Example
{
// Comment
}
```
errors right now.

@warrenseine I'm not familiar with how comments work in prettier; so I haven't taken any stab at this.

**Comment by warrenseine** [comment]
It's quite complex, but a lot of logic is already implemented within Prettier. Based on a few helpers the plugin exposes, Prettier attaches comments to the "closest" node. It's basically a binary search based on start and end positions. Yet, it gets tricky when the comment is fully enclosed by a node (eg. `class_body`), but neither leading nor trailing any node.

In that case, Prettier lets the printer decides how to print this dangling comment. In our case, it was missing in `printBraceBody()`. I'll push the fix.
