### ISSUE TITLE
Empty braces are not consistently formatted

### ISSUE THREAD

**Issue by CharlesTaylor7** [warrenseine/prettier-plugin-csharp#31]
Empty braces are printed inline for classes & structs, but printed on separate lines for `if` statements and method blocks.
e.g. 
```csharp
// inline
class Foo { }
// separate lines
if (true)
{
}
```

I'd prefer to standardize on inlining empty braces, which is how Prettier proper handles JS.

**Comment by PyroSA** [comment]
Javascript handles it as follows:

``` javascript
class foo {}
class bar {
  constructor() {}
}
class baz {
  constructor() {
    if (true) {
    }
    if (!false) {
      try {
      } catch (err) {
        console.error(err);
      } finally {
      }
    }
  }
}

```

This seems consistent.

**Comment by warrenseine** [comment]
This repository is unmaintained and the project is incomplete, don't expect anything else than a toy C# project to reformat correctly. I can accept PRs though.
