### ISSUE TITLE
How to install - doesn't seem to work

### ISSUE THREAD

**Issue by tracker1** [warrenseine/prettier-plugin-csharp#35]
I tried with the instructions in the readme... I also tried with the master branch from github directly.

With the npm release, I get a bunch of syntax errors on the first `using` statement.  With the master branch install, it doesn't have `./csharp/...`references.  I'd like to be able to use this, but I'm not sure if/what dependencies are needed etc.

OS: macOS High Sierra 10.13.3 (moving to Linux next month with new computer) (windows 10 at work)
Node: 12.9.0
dotnet: core 3 preview 8

**Comment by tracker1** [comment]
Also, in case it matters...

```
"prettier": "^1.18.2",
"prettier-plugin-csharp": "^0.6.0-development",
```

The install via readme has an `--exact` reference but isn't specifying versions if that's an issue.

**Comment by warrenseine** [comment]
I wasn't sure if it was up-to-date with the latest Prettier version, so I just tried:
```
$ mkdir prettier-csharp-test

$ cd prettier-csharp-test/

$ yarn init
yarn init v1.17.3
question name (prettier-csharp-test):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
question private:
success Saved package.json
Done in 3.46s.

$ yarn add prettier prettier-plugin-csharp
yarn add v1.17.3
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 7 new dependencies.
info Direct dependencies
├─ prettier-plugin-csharp@0.6.0-development
└─ prettier@1.18.2
info All dependencies
├─ antlr4@4.7.2
├─ is-alphabetical@1.0.3
├─ is-alphanumerical@1.0.3
├─ is-decimal@1.0.3
├─ lodash@4.17.15
├─ prettier-plugin-csharp@0.6.0-development
└─ prettier@1.18.2
Done in 4.86s.

$ echo "using System; public class C { public C() { const int? i = 42; } };" > Foo.cs

$ ./node_modules/.bin/prettier Foo.cs
using System;

public class C
{
    public C()
    {
        const int? i = 42;
    }
}
```

Maybe this needs a little bit more documentation. I'll see what I can do. In the meantime, please report any bug you encounter.

If you want to use `master`, you'll need to generate the parser. This is documented in the `README` file.
