### ISSUE TITLE
String interpolations cause hanging

### ISSUE THREAD

**Issue by crohlfs** [warrenseine/prettier-plugin-csharp#4]
Simple string interpolation seems to work fine, such as (`$"Hello {name}"`) but some more advanced ones seem to get stuck.

Here are some replications files:

```cs
class A
{
  A()
  {
    Console.WriteLine($"It's {DateTime.Now:HH:mm} now.");
  }
}
````

```cs
class A
{
  A()
  {
    Console.WriteLine($"It's {(true ? 1 : 2)} now.");
  }
}
````

Using v0.2.1-development

**Comment by warrenseine** [comment]
Yes, I'm aware of that problem (https://github.com/warrenseine/prettier-csharp/commit/971bcad6cb82c0d4e1b5e23a8eed37accbb42e7c). I would blame either the parser (ANTLR) or the grammar itself:

https://github.com/warrenseine/prettier-csharp/blob/2581449e7dd643e139974ac2c13b80b9014c2385/asset/csharp/CSharpParser.g4#L966

I won't investigate right now, but I'd welcome any patch (even if it just drops the support for formatting non-trivial string interpolation, which is not a critical feature).

**Comment by warrenseine** [comment]
In the end, it was neither ANTLR nor the grammar, but my own port of the Java snippet that deals with the string interpolation "mode" (ANTLR terminology) :) Anyway, it's fixed! I'll release soon.
