### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by SchreinerK** [warrenseine/prettier-plugin-csharp#48]
No changes since 3 years. C# 6.0 was published in 2015 . Now we have C# 11.0.
I may assume that this project is dead. :-(

Are there alternatives known?
What do you currently use to reformat C# code?

**Comment by warrenseine** [comment]
Yes it is. `dotnet-format` is a very good alternative, but it's not integrated with Prettier.

**Comment by SchreinerK** [comment]
Thx. `dotnet-format` does not do some things the way I would like it to ;-) 
I found also an active project https://github.com/belav/csharpier.
It seems that it is a port of Prettier especially for C#.
