### ISSUE TITLE
Using formatting

### ISSUE THREAD

**Issue by wanton7** [warrenseine/prettier-plugin-csharp#7]
I checked the diff and current using (disposable) formatting looks bad. You should really think of adding curly brackets when you format to multiple lines.

```csharp
            using (var v = BeginScope())
                using (A a = new A())
                    using (
                        A
                            a = new A(),
                            b = new A()
                    )
                        using (BeginScope())
                            return;
```
to
```csharp
            using (var v = BeginScope())
            {
                using (A a = new A())
                {
                    using (
                        A
                            a = new A(),
                            b = new A()
                    ) 
                    {
                        using (BeginScope())
                            return;
                    }
                }
            }
```

Also whole idea of multiple `using` statements after each other without curly brackets is to avoid nesting. I would rather see prettier avoiding nesting of `using` statements much as possible, if it can be avoided. Nesting them also hurts readability and make lines longer. I would prefer to see original code below in our company's code instead of that formatted one.

```csharp
            using (var v = BeginScope())
            using (A a = new A())
            using (A a = new A(), b = new A())
            using (BeginScope())
                return;
```

**Comment by johnnyreilly** [comment]
> whole idea of multiple using statements after each other without curly brackets is to avoid nesting. I would rather see prettier avoiding nesting of using statements much as possible, if it can be avoided. Nesting them also hurts readability and make lines longer. I would prefer to see original code below in our company's code instead of that formatted one.

very much agree about the not nesting `using` statements

**Comment by warrenseine** [comment]
Thanks for the contributions!

I agree the current setup is a waste of space. To be honest, this is just the simplest I could come up with (a `using` is just a block and all blocks are treated the same, hence the indentation and the removal of braces when there is only one statement).

The `using` blocks deserve special treatment indeed. I will try to address the different problems in separate comments below later.

**Comment by warrenseine** [comment]
I personally don't think that we should indent based on statement semantics. Why make a difference between nested `for`s (which you would indent, I suppose) and `using`s? They both express a scope and the second statement may reference the first, so reducing nesting is a weak benefit for the confusion it could bring.

Anyway, I haven't seen it explicitly in a styling guide, but it is common practice in C#, even in the code base I work on, so it makes sense to fix it. I've pushed the change for `using`, `lock`, and `fixed` statements.

**Comment by warrenseine** [comment]
The indentation for multiple-variable declarations is another topic, and doesn't seem specific to `using` statements (though I agree it exposes the problem). Please open a separate issue if you would like to change it so we limit each discussion to a single topic.

**Comment by wanton7** [comment]
Our company goes by this https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md because it's the coding style that .NET CoreFX uses.
It states

> One exception is that a using statement is permitted to be nested within another using statement by starting on the following line at the same indentation level, even if the nested using contains a controlled block.
